print("Гpyna 4") 
text_file = open("D:\students4.txt", "wt") 
text_file.write("Дашкевич Данило, 5 балів\n") 
text_file.write("Євдокименко Олександр, 10 балів\n") 
text_file.write("Карбівничный Володимир, 0 балів\n") 
text_file.write("Лукін Володимир, 7 балів\n") 
text_file.close() 
 
print("Гpyna 5") 
text_file = open("D:\students5.txt", "wt") 
text_file.write("Мазур Максим, 4 балів\n") 
text_file.write("Микуланинець Володимир, 5 балів\n") 
text_file.write("Муляр Вікторія, 10 балів\n") 
text_file.write("Омелянчук Роман, 8 балів\n") 
text_file.close() 
 
print("Гpyna 6") 
text_file = open("D:\students6.txt", "wt") 
text_file.write("Петрушка Кирило, 12 балів\n") 
text_file.write("Піць Андрій, 9 балів\n") 
text_file.write("Сухина Денис, 6 балів\n") 
text_file.write("Третьякова Вікторія, 0 балів\n") 
text_file.close()


input()